### ISSUE TITLE
Android export wraps strings at variables leading to unwanted spaces in final string

### ISSUE THREAD

**Issue by alex-goodnature** [dittowords/cli#49]
For example:
```
Hello {{name}}!
```

Becomes:
```
<string name="greeting" ditto_api_id="greeting">
    Hello 
    <xliff:g id="name" example="Steve">%1$s</xliff:g>
    !
<string>
```

Which is rendered as:
```
Hello Steve !
```

**Comment by azjgard** [comment]
Hi @alex-goodnature, thanks for reporting this as well. Like your [other issue](https://github.com/dittowords/cli/issues/48), this one is prioritized for triage tomorrow, and I'll respond back with an update ASAP.

**Comment by azjgard** [comment]
Hi @alex-goodnature, we just realized a fix for this as well!
<img width="643" alt="image" src="https://user-images.githubusercontent.com/19500384/219078273-9e0aab6b-c4b8-48b0-b8f2-c4b743769d60.png">
Feel free to re-open if you still encounter any problems 🙏

**Comment by darko-ristanovic** [comment]
@azjgard This fix created problem for Android platform, we are not able to build app because of `space="preserve" `argument. It's not recognised. We have multiple apps with this issue and have to remove this attribute manually every time. Could you please look into that? I'm sure we're not the only one facing this problem after latest update. Cheers.

**Comment by alex-goodnature** [comment]
@azjgard Cool. Thanks.
