### ISSUE TITLE
Feature Request: Pull arguments

### ISSUE THREAD

**Issue by mramosbhz** [dittowords/cli#90]
It should be great to add arguments in the pull command such as:
```
-c, --config <file_path>                        Set the path to the config.yml file
-p, --projects project_name1,project_name2      Specify from which project to pull
```

### -c, --config <file_path>
The `parseSourceInformation` method from `config` it's already prepared for this:
![image](https://github.com/dittowords/cli/assets/2117093/f6053289-a42c-4840-bb61-9fb5d37c09a9)

But not pull:
![image](https://github.com/dittowords/cli/assets/2117093/054e575d-d211-4217-81f9-2fecf5e44edd)

### -p, --projects project_name1,project_name2
I think that it can be passed in the same `parseSourceInformation` method.

**Comment by azjgard** [comment]
Hi @mramosbhz,

Thanks so much for opening this issue!

The suggested argument additions are very reasonable. Would you mind providing some additional context on your use-case that requires being able to specify projects / configurations via command line args? Or does your request come from a place of wanting improved ergonomics?

In most cases that we see, customers opt to handle separate projects by having a separate `config.yml` for each, and then in their development scripts change directory to the appropriate place before running the relevant Ditto CLI commands.

**Comment by mramosbhz** [comment]
Hello @azjgard, 
Thanks for answering me.

[TL;DR;](#user-content-tl-dr)

We create a new Figma prototype linked with a new project in Ditto for every new feature in our products.
We're currently dealing with unaccountable text files, distributed in different directory levels inside our repositories, to handle our multi-language product (an i18n folder for each front-end component).
We're planning to maintain those files, but do some links to Ditto CLI output files, for each project.

Reading the documents, I found that I can use the `DITTO_TEXT_DIR` environment variable to define where will be the output directory from Ditto CLI. (I was planning to ask an argument for this 😁)

Testing the CLI, I tried to change the directory before running `npx @dittowords/cli pull`. The CLI ignored the existent config.yml, and created a `./ditto` folder in the project's root with a default `config.yml`. I'm putting all of my settings there. Maybe I'm doing something wrong or facing some issues with my computer.

<h1 id="tl-dr">TL;DR;</h1>

I'm asking for these new arguments for the following reasons:
### -c, --config <file_path>
Specify from which configuration file the CLI will read.
Even if I could run the pull command inside subdirectories, this argument can save us from creating a script to navigate through directories to run some commands.

### -p, --projects project_name1,project_name2
Specify which project I want to update.
If the prior argument exists, I could divide projects per file. So this argument wouldn't be that much necessary.
If I have to keep all the projects in the same config file, it would be great to have this argument to avoid updating all files from all projects. It can save resources from Ditto. Instead of transferring 10~50 project data, it'll be a few projects.

Maybe I can create a fork of the repository to produce some POC. What do you think about it?

Feel free to contact me with feedback or ask me for more information.

Thank you.

**Comment by azjgard** [comment]
Thanks so much for the additional context!

> Testing the CLI, I tried to change the directory before running `npx @dittowords/cli pull`. The CLI ignored the existent config.yml, and created a ./ditto folder in the project's root with a default config.yml. I'm putting all of my settings there. Maybe I'm doing something wrong or facing some issues with my computer.

It does seem like something is not functioning correctly here 🤔 The expected behavior is that the CLI always operates by looking for `./ditto/config.yml` relative to the current working directory; if you have a monorepo setup as shown below, changing into either `project1` or `project2` and running `npx @dittowords/cli pull` should read from the corresponding configuration files for each directory, or should create a new `ditto` folder with a new configuration file if they don't already exist:
```
root/
├── project1/
│   ├── ditto/
│   |   ├── config.yml
├── project2/
│   ├── ditto/
│   |   ├── config.yml
```
To confirm, is the behavior I've described above different from what you're experiencing? I did some testing on my end and it appears to be working as described for me: I have a different configuration in each folder, and when I run the CLI from a given folder, it only pulls data for the projects / components listed in the corresponding configuration.

> Even if I could run the pull command inside subdirectories, this argument can save us from creating a script to navigate through directories to run some commands.

To be clear here, if there were an option to specify which configuration to use as a command line argument, and if you always needed to provide that argument when running the CLI, would you not also end up creating scripts to encapsulate those arguments?

e.g. without the command line argument added
```json
{
  "ditto:pull:project1": "cd project1 && npx @dittowords/cli pull",
  "ditto:pull:project1": "cd project2 && npx @dittowords/cli pull"
}
```

e.g. with the command line argument added
```json
{
  "ditto:pull:project1": "npx @dittowords/cli pull -c ./project1/ditto/config.yml",
  "ditto:pull:project1": "npx @dittowords/cli pull -c ./project2/ditto/config.yml"
}
```

It seems to me like the command line argument would be enabling an alternative method of configuration specification, but would not necessarily be enabling any new functionality that does not currently exist. Does that line up with your thoughts as well? Let me know if there's anything I'm misunderstanding!

**Comment by mramosbhz** [comment]
It is a problem with Windows shells (command and PowerShell). After many tries, I could only get this working using WSL (Ubuntu).

I used another approach, passing the project as a param to the npm command:
```json
{
  "ditto:pull": "cd src/base-dir-of-copy/$npm_config_project && npx @dittowords/cli pull"
}
```
I prepared a `config.yml` file in `src/base-dir-of-copy/my-project-name/ditto` and ran the command:
```sh
npm run ditto:pull --project=my-project-name
```
This way I can have multiple project directories and one single command.

Could you please look at this command behavior in the Windows environment?

Thanks for your attention.

**Comment by mramosbhz** [comment]
I made some adjustments here.
It's working on Windows now, but not on other OS. Cross-environment libraries are not working very well.
Since our main use is on Windows, we won't consider this an issue anymore.
